---
- name: Create a RHEL For Edge Image in your Fleet Management Account
  hosts: CRC
  gather_facts: false
  vars:
    imageName: "admillerAnsibleTest7"
  tasks:
    - name: Create an image
      maxamillion.fleetmanager.create_image:
        name: "{{ imageName }}"
        packages:
          - vim-enhanced
          - tmux
        custom_repositories:
          - name: "test 1234"
        custom_packages:
          - bear
        ssh_user: admiller
        ssh_pubkey: |-
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKsfN0OHqBBk306pOehDFJ9ZPhjrOlym1QrQQL6OmnO3WskPHXqtrL4WtwJCQvrgUVZ4A65ax4lLz/EygoIpv997aYh0pGFAs0l8peHWsDkMalRr2bxZ5KbwjVyAPv5bJ8Qu1h+PY8Qf6aW+hAYfefU5CHzPian6l4R+++JO0//l8ugZZtujSPgPCllz+eJWuI44Qou0/XrrGTqwjwkb8hJjFlBEgGmPt45gjghBn9/xc6H1n8cyI1jDxRG66Q4dVD0pwCopg6WDeC7LReDvUFB8N9BI5teUugyc/x6j97eykZ07xw6tamerVEC+vFMvxPmkCs3H8zN66h9u+8+CLIqSm7A0StbM+p7REthAtZdNvDuL/usz1pqbRMM+MtaPuNL/LhN12JYK7aRjm84D4Hfs25AzwD20ottWVoHKTi335m3L0egNQ6mMS4hvbDp6q05vuyNtl7sUFGkBv46H3oX26UNoEs6RIM/LLlBkXEfulF6fYu3HIAwN3hHeXsP773RwT27KXU3MMGVWjDMfO+AOFcOUX0jVC6mvC4iYZbseNiDdqcF27sCYgmHUPlGb2Dait1Zj2f7lShOyIjzjR6RXUvu9JlKiICPDBtgzCQPz/IAsp0SqLGPxZojLkfNaVWoF4j+XDqhHSN07Bg36MXgR4vN//PeKY9U3NPYMsdJQ==
      register: createimage_output

    - debug: var=createimage_output

    - name: wait until image build is successful
      maxamillion.fleetmanager.images_info:
        id: "{{ createimage_output['image']['ID'] }}"
      register: imageinfo_output 
      until: imageinfo_output['images']['Status'] == "SUCCESS"
      retries: 300
      delay: 10


    - debug: var=imageinfo_output

