---
- name: Delete a custom repo
  hosts: CRC
  gather_facts: false
  vars:
    repo_name: 'AnsibleRepo123'
  tasks:
    - name: Delete a group
      maxamillion.fleetmanager.custom_repositories:
        name: '{{ repo_name }}'
        state: 'absent'
      register: delete_repo_output

    # - debug: var=delete_repo_output
