---
- name: Filter systems
  hosts: CRC
  gather_facts: false
  tasks:
    - name: Filter systems by insight facts
      consoledot.edgemanagement.filter_systems:
        host_type: '{{ host_type }}'
        display_name: '{{ display_name }}'
        ipv4: '{{ ipv4 }}'
        # os_release: '{{ os_release }}'
        # cores_per_socket: '{{ cores_per_socket }}'
        # infrastructure_vendor: '{{ kvm }}'
        # number_of_cpus: '{{ number_of_cpus }}'
        # number_of_sockets: '{{ number_of_sockets }}'
        # os_kernel_version: '{{ os_kernel_version }}'
        # enabled_services: '{{ enabled_services }}'
        installed_services: '{{ installed_services }}'
        os_release: '8.5'
        cores_per_socket: 1
        infrastructure_vendor: 'kvm'
        number_of_cpus: 1
        number_of_sockets: 1
        os_kernel_version: '4.18.0'
        enabled_services:
          - 'firewalld'
          - 'rhcd'
      register: filtered_systems
    - name: Save filtered systems
      set_fact:
        filtered_systems: '{{ filtered_systems }}'
        cacheable: yes

    - debug: var=filtered_systems['edge_device_ids']
    # - debug: var=filtered_systems['matched_systems']
