---
- name: Filter systems
  hosts: CRC
  gather_facts: false
  tasks:
    - name: Filter systems by insight facts
      consoledot.edgemanagement.filter_systems:
        host_type: 'edge'
        display_name: 'frontend'
        ipv4: '192.168.122.[22:199]'
        os_release: '8.5'
        cores_per_socket: 1
        infrastructure_vendor: 'kvm'
        number_of_cpus: 1
        number_of_sockets: 1
        os_kernel_version: '4.18.0'
        enabled_services:
          - 'firewalld'
          - 'rhcd'
        installed_services:
          - 'rhsm'
          - 'rhcd'
      register: filtered_systems

    - debug: var=filtered_systems['edge_device_ids']
    # - debug: var=filtered_systems['matched_systems']
