---
- name: Update systems
  hosts: CRC
  gather_facts: false
  tasks:
    - name: Update systems to latest version using ids
      consoledot.edgemanagement.update_systems:
        uuids:
          - '160adfc2-00b1-48d5-b607-8b5ae7f4a861'
        version: 7
      register: output

    - name: Update systems to latest version within a group
      consoledot.edgemanagement.update_systems:
        groups:
          - 'updated-with-ansible'
      register: output
