---
- name: Update a RHEL for Edge Fleet Device
  hosts: CRC
  gather_facts: false
  vars:
    deviceUUID: "2ae43de4-bce7-4cfb-9039-af77458260ea"
    imageID: 6148
  tasks:
    - name: update an image
      consoledot.edgemanagement.update_image:
        id: "{{ imageID }}"
      register: updateimage_output

    - debug: var=updateimage_output

    - name: wait until image build is successful
      consoledot.edgemanagement.images_info:
        id: "{{ updateimage_output['image']['ID'] }}"
      register: imageinfo_output
      until: imageinfo_output['images']['Status'] == "SUCCESS"
      retries: 300
      delay: 10
#   - name: update a device
#     consoledot.edgemanagement.update_device:
#       client_id: "{{ deviceUUID }}"
#     register: update_output 

#   - debug: var=update_output
