---
- name: Add devices to a group
  hosts: CRC
  gather_facts: false
  tasks:
    - name: 
      consoledot.edgemanagement.add_devices_to_group:
        name: 'ansible-group-santiago'
        devices:
          - 21402 
          - 21365
          - 31601
        state: 'present'
