trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
        - stable-*

variables:
  - name: checkoutPath
    value: ansible_collections/consoledot/edgemanagement
  - name: coverageBranches
    value: main
  - name: pipelinesCoverage
    value: coverage
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:3.0.0

pool: Standard

stages:
## Sanity
  - stage: Sanity_devel
    displayName: Ansible devel sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: 'devel/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Sanity_2_13
    displayName: Ansible 2.13 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.13/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Sanity_2_12
    displayName: Ansible 2.12 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.12/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units

## Finally

  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity_devel
      - Sanity_2_13
      - Sanity_2_12
    jobs:
      - template: templates/coverage.yml
